config/routes.rb
Rails.application.routes.draw do
  get 'new/index'

  root :to => "tabla#index"
  get 'tabla/index'
  get 'tabla/new'
  post 'tabla/save'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alumno.rb
class Alumno < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def index
  end
end

app/controllers/tabla_controller.rb
class TablaController < ApplicationController
  def index

@alumno=Alumno.all
end

def new 
end 

def save
name=params[:name_field]
apellido=params[:last_name_field]
puntos=params[:scored_points_field]

@alumno=Alumno.create(name:name,last_name:apellido,scored_points:puntos)
redirect_to tabla_index_path
end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/tabla_helper.rb
module TablaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tabla</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/new/index.html.erb
<h1>Nuevo Registro</h1>

<%= form_tag tabla_save_path do %>
<label form="usuario">Usuario</label>
<%= text_field_tag :name_field%>
<%= text_field_tag :last_name_field%>
<%= text_field_tag :scored_points_field%>


<%= submit_tag "Aqui va!"%>
<%end%>

app/views/tabla/index.html.erb
<h1>tabla#index</h1>
<p>find me in app/views/tabla/index.html.erb</p>
<%=link_to "nuevo", controller: 'new'%>

<table class="table" >
<thead>
<tr>
<th>name</th>
<th>last_name</th>
<th>scored_points</th>
<th colspan="3"></th>

</tr>
<thead>
<%@alumno.each do |a|%>

<tr>
<td><%=a.name%></td>
<td><%=a.last_name%></td>
<td><%=a.scored_points%></td>
</tr>

<td class="tag is-info is-large"><%a.created_at%></td>

<%end%>